[project]
name = "server"
version = "0.1.0"
description = "磨炼你的毅力"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "Flask==3.0.3",
    "Flask-SQLAlchemy==3.1.1",
    "SQLAlchemy==2.0.35"
]
